services:
  web:
    build: .
    ports:
      - "8080:80"
    restart: always

  # ejemplo adicional: una base de datos
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: devops123
      POSTGRES_DB: miapp
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
