terraform {
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.0"
    }
  }
}

provider "local" {}

# Use of vars
resource "local_file" "file" {
  filename = var.filename
  content  = "Hi ${var.author}, this file was generated by Terraform 👋"
}